version: '3.4'

# cf.: https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd#f191
#### common partials (needs docker-compose v3.4)
x-proxy: &proxy
  http_proxy: ${http_proxy}
  https_proxy: ${https_proxy}
  no_proxy: ${no_proxy}

x-base: &base
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "5"
  # https://docs.docker.com/compose/compose-file/#restart
  #restart: on-failure # disable restart for development
  # when deployed using docker swarm, cf.: https://docs.docker.com/compose/compose-file/#restart_policy
#########

volumes:
  json-volume:    # suricata json input -> logstash
  elastic-volume: # elasticsearch data
  rules-volume:   # scirius rules

services:

  suricata:
    <<: *base
    # Reference:
    # - https://github.com/dtag-dev-sec/tpotce/blob/master/docker/suricata/docker-compose.yml
    # Good suricata images, cf.:
    # - https://github.com/dtag-dev-sec/tpotce/blob/master/docker/suricata/Dockerfile
    # - https://hub.docker.com/r/jasonish/suricata/
    # - https://github.com/StamusNetworks/suricata-docker/blob/master/Dockerfile
    image: dtagdevsec/suricata:1804
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW

    volumes:
      #- ./suricata/config/suricata.yaml:/etc/suricata/suricata.yaml:ro
      #- ./suricata/config/ethtool.conf:/etc/supervisor/conf.d/ethtool.conf:ro
      - json-volume:/var/log/suricata
      - rules-volume:/etc/suricata/rules:rw
      - ./suricata/pcap:/pcap
    command: bash -c "suricata -c /etc/suricata/suricata.yaml -r /pcap/log.pcap"

  elasticsearch:
    build:
      context: ./elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      # single-node, cf.:
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run
      transport.type: local
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic-volume:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:5.5.0
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/conf.d:/usr/share/logstash/pipeline:ro
      - json-volume:/var/log/suricata:ro
    hostname: suricata
    environment:
      - XPACK_MONITORING_ENABLED=false
      #- LOG_LEVEL=debug

  kibana:
    build:
      context: ./kibana
    # volumes:
    #    - "./kibana/config/:/etc/kibana/"
    ports:
       - "5601:5601"
    depends_on:
      - elasticsearch

  scirius:
    image: stamus/scirius:elk5
    ports:
       - "8080:80"
    volumes:
      - ./scirius/config:/etc/scirius:ro
      - ./suricata/config/suricata.yaml:/etc/suricata/suricata.yaml:ro
      - rules-volume:/etc/suricata/rules:rw
    depends_on:
      - elasticsearch
      - kibana
      - evebox

  evebox:
    image: jasonish/evebox:latest
    ports:
       - "5636:5636"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

  eve:
    image: busybox
    volumes:
      - json-volume:/json
      - ./eve:/eve
    command: ash -c "cp /json/eve.json /eve/eve.json"
